"""Initial schema

Revision ID: 11724b25a0e1
Revises: 
Create Date: 2026-06-24 22:51:37.489034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11724b25a0e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('input_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_events_user_id'), 'guardrail_events', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('plan_tier', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('monthly_audit_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brands_name_city', 'brands', ['name', 'city'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_index(op.f('ix_brands_user_id'), 'brands', ['user_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('llm_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_cited', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('gaps', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('planned_actions', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('remediations', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('competitors', sa.JSON(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('anomalies', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('report', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('predicted_geo_score', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('workflow_run_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audits_created_at', 'audits', ['created_at'], unique=False)
    op.create_index('idx_audits_status', 'audits', ['status'], unique=False)
    op.create_index(op.f('ix_audits_brand_id'), 'audits', ['brand_id'], unique=False)
    op.create_table('audit_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nps_score', sa.Integer(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_feedback_audit_id'), 'audit_feedback', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_feedback_user_id'), 'audit_feedback', ['user_id'], unique=False)
    op.create_table('llm_call_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_calls_audit_id', 'llm_call_logs', ['audit_id'], unique=False)
    op.create_index('idx_llm_calls_created_at', 'llm_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_user_id'), 'llm_call_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_call_logs_user_id'), table_name='llm_call_logs')
    op.drop_index('idx_llm_calls_created_at', table_name='llm_call_logs')
    op.drop_index('idx_llm_calls_audit_id', table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    op.drop_index(op.f('ix_audit_feedback_user_id'), table_name='audit_feedback')
    op.drop_index(op.f('ix_audit_feedback_audit_id'), table_name='audit_feedback')
    op.drop_table('audit_feedback')
    op.drop_index(op.f('ix_audits_brand_id'), table_name='audits')
    op.drop_index('idx_audits_status', table_name='audits')
    op.drop_index('idx_audits_created_at', table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_brands_user_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index('idx_brands_name_city', table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_guardrail_events_user_id'), table_name='guardrail_events')
    op.drop_table('guardrail_events')
    # ### end Alembic commands ###
